import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "@/styles/globals.css";
import Providers from "@/lib/Providers";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <Providers>
      <html lang="en">
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <body className={`${inter.className}`}>
          <main className="max-w-[1280px] mx-auto">{children}</main>
        </body>
      </html>
    </Providers>
  );
}
